- debug:
    msg: "Configuring sql node"
- name: Create the configuration file in /etc directory with my.cnf as its name
  template:
    src: sql.j2
    dest: /etc/my.cnf
- name: Start the SQL Node by starting the MySQL server
  service:
    name: mysql
    state: started