- debug:
    msg: "Configuring data node"
- name: Create the configuration file in /etc directory with my.cnf as its name
  template:
    src: data.j2
    dest: /etc/my.cnf
- name: create the new directory for the database data
  command: mkdir -p /var/lib/mysql-cluster
- name: Start the data node
  command: ndbd